#!/bin/bash
#
# theme-switch.sh — called by dark-notify with "dark" or "light" as $1
#
# This script is the single entry point for tools that cannot detect
# macOS appearance changes on their own. Currently handles:
#   - tmux: sources the matching theme-{dark,light}.conf
#   - Claude Code: updates ~/.claude.json theme (not reliably picked up live)
#   - lazygit: rebuilds config.yml from config.base.yml + active theme
#
# opencode: uses "system" theme — auto-switches with macOS appearance natively.
#
# Neovim handles appearance changes natively via mode 2031
# (forwarded by tmux 3.6+, supported by Neovim 0.12+).

MODE="$1"

if [ "$MODE" != "dark" ] && [ "$MODE" != "light" ]; then
  echo "Usage: theme-switch.sh <dark|light>" >&2
  exit 1
fi

# --- tmux ---
# Use full path — launchd runs with a minimal PATH that excludes /opt/homebrew/bin
TMUX_BIN="/opt/homebrew/bin/tmux"
if "$TMUX_BIN" list-sessions &>/dev/null; then
  "$TMUX_BIN" source-file "$HOME/.config/tmux/theme-${MODE}.conf"
fi

# --- Claude Code ---
# Updates ~/.claude.json theme. Claude Code picks up the change immediately.
CLAUDE_THEME="${MODE}-daltonized"
CLAUDE_JSON="$HOME/.claude.json"
if [ -f "$CLAUDE_JSON" ]; then
  /opt/homebrew/bin/jq --arg theme "$CLAUDE_THEME" '.theme = $theme' "$CLAUDE_JSON" > /tmp/claude.json \
    && mv /tmp/claude.json "$CLAUDE_JSON"
fi

# --- lazygit ---
LAZYGIT_DIR="$HOME/.config/lazygit"
{
  echo "# GENERATED FILE — do not edit directly."
  echo "# Edit config.base.yml for settings, theme-dark.yml / theme-light.yml for colors."
  echo "# Regenerated by dark-notify/theme-switch.sh on appearance change."
  echo ""
  cat "$LAZYGIT_DIR/config.base.yml"
  cat "$LAZYGIT_DIR/theme-${MODE}.yml"
} > "$LAZYGIT_DIR/config.yml"
