tap "homebrew/bundle"
tap "homebrew/services"
tap "jesseduffield/lazydocker"
# Improved shell history for zsh, bash, fish and nushell
brew "atuin"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Mozilla CA certificate store
brew "ca-certificates"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Library for command-line editing
brew "readline"
# Official Amazon AWS command-line interface
brew "awscli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Core application library for C
brew "glib"
# Vector graphics library with cross-device output support
brew "cairo"
# GNU multiple precision arithmetic library
brew "gmp"
# GNU File, Shell, and Text utilities
brew "coreutils"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# Emacs dependency management
brew "cask"
# Cross-platform make
brew "cmake"
# Fix common misspellings in source code and text files
brew "codespell"
# Load/unload environment variables based on $PWD
brew "direnv"
# Isolated development environments using Docker
brew "docker-compose"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# Library for encoding and decoding .avif files
brew "libavif"
# GitHub command-line tool
brew "gh"
# Git extension for versioning large files
brew "git-lfs"
# C/C++ and Java libraries for Unicode and globalization
brew "icu4c@76"
# OpenType text shaping engine
brew "harfbuzz"
# Library to render SVG files using Cairo
brew "librsvg"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Popular GNU data compression program
brew "gzip"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "k9s"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Simple terminal UI for git commands
brew "lazygit"
# Fast and powerful Git hooks manager for any type of projects
brew "lefthook"
# X.509 and CMS library
brew "libksba"
# NaCl networking and cryptography library
brew "libsodium"
# YAML Parser
brew "libyaml"
# General-purpose lossless data-compression library
brew "zlib"
# Open source relational database management system
brew "mysql@8.0"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# HTTP/2 C Library
brew "nghttp2"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Object-relational database system
brew "postgresql@14"
# Monitor data's progress through a pipe
brew "pv"
# Persistent key-value database, with built-in net interface
brew "redis"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Database of common MIME types
brew "shared-mime-info"
# Opinionated Lua code formatter
brew "stylua"
# Tool to build, change, and version infrastructure
brew "terraform"
# Code-search similar to ack
brew "the_silver_searcher"
# Instant terminal sharing
brew "tmate"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
# A simple terminal UI for docker, written in Go
brew "jesseduffield/lazydocker/lazydocker"
# Command-line interface for 1Password
cask "1password-cli"
# Securely stores and accesses AWS credentials in a development environment
cask "aws-vault"
# Web browser focusing on privacy
cask "brave-browser"
# API documentation browser and code snippet manager
cask "dash"
# App to build and share containerised applications and microservices
cask "docker"
# Web browser
cask "firefox"
cask "font-blex-mono-nerd-font"
cask "font-monaspace-nerd-font"
cask "font-symbols-only-nerd-font"
# Web browser
cask "google-chrome"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Replacement for Docker Desktop
cask "orbstack"
# Plugin for AWS CLI to start and end sessions that connect to managed instances
cask "session-manager-plugin"
# Team communication and collaboration software
cask "slack"
# Native GUI tool for relational databases
cask "tableplus"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
# HTML to PDF renderer
cask "wkhtmltopdf"
